services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: novabank-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres_secure_2026@postgres:5432/novabank_db?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=novabank_ultra_secure_jwt_secret_key_2026_xyz987
      - JWT_EXPIRES_IN=1d
      - JWT_REFRESH_SECRET=novabank_refresh_secret_key_2026_abc123
      - JWT_REFRESH_EXPIRES_IN=7d
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=100
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  postgres:
    image: postgres:16-alpine
    container_name: novabank-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_2026
      POSTGRES_DB: novabank_db
    volumes:
      - novabank_pg_data:/var/lib/postgresql/data
      - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d novabank_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: novabank-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - novabank_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: novabank-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  novabank_pg_data:
  novabank_redis_data:
